-- Script was generated by Devart dbForge Studio Express for MySQL, Version 5.0.82.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/1/2012 2:09:33 PM
-- Server version: 5.5.16
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for database ugst
--
DROP DATABASE IF EXISTS ugst;
CREATE DATABASE IF NOT EXISTS ugst
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Set default database
--
USE ugst;

--
-- Definition for table attachments
--
CREATE TABLE IF NOT EXISTS attachments (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  date_added DATETIME NOT NULL,
  wosksheet_id BIGINT(20) UNSIGNED NOT NULL,
  worksheet_order TINYINT(4) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table reviews
--
CREATE TABLE IF NOT EXISTS reviews (
  id VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table roles
--
CREATE TABLE IF NOT EXISTS roles (
  id TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  role_name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX roleName (role_name)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table select_options
--
CREATE TABLE IF NOT EXISTS select_options (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) NOT NULL,
  subtype VARCHAR(255) NOT NULL,
  code VARCHAR(20) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(2048) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 38
AVG_ROW_LENGTH = 442
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table statuses
--
CREATE TABLE IF NOT EXISTS statuses (
  id TINYINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  status VARCHAR(255) NOT NULL,
  status_description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX status (status)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table students
--
CREATE TABLE IF NOT EXISTS students (
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  uid VARCHAR(255) NOT NULL,
  email_id VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (uid)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table users
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  emailId VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  lastModifiedTime TIMESTAMP DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX emailId (emailId),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 24
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table worksheets
--
CREATE TABLE IF NOT EXISTS worksheets (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  student_id VARCHAR(255) NOT NULL,
  created_date DATETIME NOT NULL,
  status_id TINYINT(4) UNSIGNED NOT NULL,
  lastModifiedBy VARCHAR(255) NOT NULL,
  lastModifieddate DATETIME NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table attachments
--
-- Table ugst.attachments does not contain any data (it is empty)

-- 
-- Dumping data for table reviews
--
-- Table ugst.reviews does not contain any data (it is empty)

-- 
-- Dumping data for table roles
--
INSERT INTO roles VALUES 
  (1, 'admin'),
  (3, 'creator'),
  (2, 'reviewer');

-- 
-- Dumping data for table select_options
--
INSERT INTO select_options VALUES 
  (1, 'block', 'financial', '00', 'Unavailable', 'Unavailable or not collected'),
  (2, 'block', 'financial', '01', 'Eligible', 'Financial eligibility'),
  (3, 'block', 'financial', '02', 'Contract & Loan', 'Contract and loan problem'),
  (4, 'block', 'financial', '03', 'SAR > Select', 'SAR balance > or = to select balance'),
  (5, 'block', 'financial', '04', 'Severed Services', 'Severed university services'),
  (6, 'block', 'financial', '05', 'Delin. SCCU', 'Delinquent account at SCCU'),
  (7, 'block', 'financial', '06', 'SEV+DEL SCCU', 'Severed and delinquent account at SCCU'),
  (8, 'block', 'financial', '07', 'Adjudged', 'Adjudged account'),
  (9, 'block', 'financial', '08', 'Loan Interview', 'NDSL or house loan interview'),
  (10, 'block', 'financial', '09', 'BAL+LN INT', 'SAR bal not < sel bal & NDSL/HS loan int'),
  (11, 'block', 'financial', '10', 'SEV+EXIT INT', 'Severed services and exit interview'),
  (12, 'block', 'financial', '11', 'DEL+EXIT INT', 'Delinquent account and exit interview'),
  (13, 'block', 'financial', '12', 'DEL SEV+EXIT INT', 'Delinquent severed and exit interview'),
  (14, 'block', 'financial', '13', 'ADJ+EXIT INT', 'Adjudged and exit interview'),
  (15, 'block', 'financial', '99', 'UNDEF INELIGIBLE', 'Undefined Ineligible'),
  (16, 'block', 'judicial', '00', 'Unavailable', 'Unavailable or not collected'),
  (17, 'block', 'judicial', '01', 'Eligible', 'Eligible'),
  (18, 'block', 'judicial', '02', 'NO-REG OK-REC', 'Cannot register, records may be released'),
  (19, 'block', 'judicial', '03', 'OK-REG NO-REC', 'May register, do not release records'),
  (20, 'block', 'judicial', '04', 'NO-REG NO-REC', 'Cannot register, do not release records'),
  (21, 'block', 'judicial', '05', 'NOTIFY JUD', 'Notify judiciary of students'),
  (22, 'decision', 'prior_reenrollment', '1A', NULL, NULL),
  (23, 'decision', 'prior_reenrollment', '2A', NULL, NULL),
  (24, 'decision', 'prior_reenrollment', '2F', NULL, NULL),
  (25, 'decision', 'prior_reenrollment', '3A', NULL, NULL),
  (26, 'decision', 'prior_reenrollment', '3F', NULL, NULL),
  (27, 'decision', 'prior_reenrollment', '4X', NULL, NULL),
  (28, 'decision', 'prior_reenrollment', '50', NULL, NULL),
  (29, 'decision', 'prior_reenrollment', '60', NULL, NULL),
  (30, 'decision', 'prior_reenrollment', '80', NULL, NULL),
  (31, 'decision', 'prior_reenrollment', '86', NULL, NULL),
  (32, 'decision', 'prior_reenrollment', '6M', NULL, NULL),
  (33, 'decision', 'prior_reenrollment', '6X', NULL, NULL),
  (34, 'decision', 'prior_reenrollment', '8A*', NULL, NULL),
  (35, 'decision', 'prior_reenrollment', '8A', NULL, NULL),
  (36, 'decision', 'prior_reenrollment', 'RC', NULL, NULL),
  (37, 'decision', 'prior_reenrollment', '8N', NULL, NULL);

-- 
-- Dumping data for table statuses
--
-- Table ugst.statuses does not contain any data (it is empty)

-- 
-- Dumping data for table students
--
-- Table ugst.students does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES 
  (20, 'rajankz@gmail.com', '6a276042bc255e00056fc3ce1577e9c91065f2d9', 'rajankz', '1', 1, '2012-07-16 12:57:06'),
  (22, 'simple@abc.org', '6a276042bc255e00056fc3ce1577e9c91065f2d9', 'simple', '2', 1, '0000-00-00 00:00:00'),
  (23, 'hello@world.com', '935613726ca7a2b0910b52b5a57b9f9447abd47b', 'creator', '3', 1, '0000-00-00 00:00:00');

-- 
-- Dumping data for table worksheets
--
-- Table ugst.worksheets does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;